services:
  database:
    image: postgres:16
    container_name: clinic_db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clinic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinic_network

volumes:
  postgres_data:

networks:
  clinic_network:
    driver: bridge